base_images:
  centos:
    name: centos
    namespace: origin
    tag: stream8
build_root:
  from_repository: true
images:
- dockerfile_path: Dockerfile
  to: agent-qe-oink
promotion:
  namespace: ci
  tag: latest
releases:
  latest:
    integration:
      include_built_images: true
      name: "4.13"
      namespace: ocp
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: hello
  commands: echo hello world
  container:
    clone: false
    from: centos
zz_generated_metadata:
  branch: master
  org: bmanzari
  repo: vnc-recorder
