base_images:
  ansible:
    name: "4.13"
    namespace: ocp
    tag: ansible
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  openstack-installer:
    name: "4.13"
    namespace: ocp
    tag: openstack-installer
  upi-installer:
    name: "4.13"
    namespace: ocp
    tag: upi-installer
releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: nightly
      version: "4.13"
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.13"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: agent-installer-rehearse-sno-v4-connected-static
  cluster: build05
  interval: 960h
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      ARCHITECTURE: amd64
      AUX_HOST: openshift-qe-055.arm.eng.rdu2.redhat.com
      BASE_DOMAIN: agentinstaller.com
      CLUSTER_NAME: 413-sno-v4-connected-static
      DEPLOYMENT_TYPE: sno
      DISCONNECTED: "false"
      FIPS: "false"
      IP_STACK: v4
      PROXY: "false"
    workflow: baremetal-lab-agent
- as: agent-installer-rehearse-sno-v4-disconnected-static
  cluster: build05
  interval: 960h
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      ARCHITECTURE: amd64
      AUX_HOST: openshift-qe-055.arm.eng.rdu2.redhat.com
      BASE_DOMAIN: agentinstaller.com
      CLUSTER_NAME: 413-sno-v4-disconnected-static
      DEPLOYMENT_TYPE: sno
      DISCONNECTED: "true"
      FIPS: "false"
      IP_STACK: v4
      PROXY: "false"
    workflow: baremetal-lab-agent
- as: agent-installer-sno-rehearse-v6
  cluster: build05
  interval: 960h
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      ARCHITECTURE: amd64
      AUX_HOST: openshift-qe-055.arm.eng.rdu2.redhat.com
      BASE_DOMAIN: agentinstaller.com
      CLUSTER_NAME: sno-rehearse-413-v6
      DEPLOYMENT_TYPE: sno
      DISCONNECTED: "false"
      FIPS: "false"
      IP_STACK: v6
      PROXY: "false"
    workflow: baremetal-lab-agent
- as: agent-installer-sno-rehearse-v4v6
  cluster: build05
  interval: 960h
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      ARCHITECTURE: amd64
      AUX_HOST: openshift-qe-055.arm.eng.rdu2.redhat.com
      BASE_DOMAIN: agentinstaller.com
      CLUSTER_NAME: sno-rehearse-413-v4v6
      DEPLOYMENT_TYPE: sno
      DISCONNECTED: "false"
      FIPS: "false"
      IP_STACK: v4v6
      PROXY: "false"
    workflow: baremetal-lab-agent
- as: agent-installer-compact-rehearse-v4
  cluster: build05
  interval: 960h
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      ARCHITECTURE: amd64
      AUX_HOST: openshift-qe-055.arm.eng.rdu2.redhat.com
      BASE_DOMAIN: agentinstaller.com
      CLUSTER_NAME: compact-rehearse-413-v4
      DEPLOYMENT_TYPE: compact
      DISCONNECTED: "false"
      FIPS: "false"
      IP_STACK: v4
      PROXY: "false"
    workflow: baremetal-lab-agent
- as: agent-installer-compact-rehearse-v6
  cluster: build05
  interval: 960h
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      ARCHITECTURE: amd64
      AUX_HOST: openshift-qe-055.arm.eng.rdu2.redhat.com
      BASE_DOMAIN: agentinstaller.com
      CLUSTER_NAME: compact-rehearse-413-v6
      DEPLOYMENT_TYPE: compact
      DISCONNECTED: "false"
      FIPS: "false"
      IP_STACK: v6
      PROXY: "false"
    workflow: baremetal-lab-agent
- as: agent-installer-compact-rehearse-v4v6
  cluster: build05
  interval: 960h
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      ARCHITECTURE: amd64
      AUX_HOST: openshift-qe-055.arm.eng.rdu2.redhat.com
      BASE_DOMAIN: agentinstaller.com
      CLUSTER_NAME: compact-rehearse-413-v4v6
      DEPLOYMENT_TYPE: compact
      DISCONNECTED: "false"
      FIPS: "false"
      IP_STACK: v4v6
      PROXY: "false"
    workflow: baremetal-lab-agent
zz_generated_metadata:
  branch: master
  org: openshift
  repo: verification-tests
  variant: agent-installer-rehearse-4.13
