base_images:
  ansible:
    name: "4.12"
    namespace: ocp
    tag: ansible
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  openstack-installer:
    name: "4.12"
    namespace: ocp
    tag: openstack-installer
  upi-installer:
    name: "4.12"
    namespace: ocp
    tag: upi-installer
releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: nightly
      version: "4.12"
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.12"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: agent-installer-SNO-rehearse
  cluster: build05
  interval: 960h
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      DEPLOYMENT_TYPE: SNO
      AUX_HOST: openshift-qe-055.arm.eng.rdu2.redhat.com
      CLUSTER_NAME: sno_rehearse_412
      BASE_DOMAIN: agent_installer.com
      IP_STACK: v4v6 #v4, v6 or v4v6
      DISCONNECTED: false #true or false
      PROXY: false #true or false
      FIPS: false #true or false
      ARCHITECTURE: amd64
    post:
    - chain: baremetal-lab-post-agent
    pre:
    - chain: baremetal-lab-install-agent
zz_generated_metadata:
  branch: master
  org: openshift
  repo: verification-tests
  variant: agent-installer-rehearse-4.12
