base_images:
  ansible:
    name: "4.15"
    namespace: ocp
    tag: ansible
  cli:
    name: "4.15"
    namespace: ocp
    tag: cli
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  tests-private-postupg:
    name: tests-private
    namespace: ci
    tag: "4.19"
  tests-private-preupg:
    name: tests-private
    namespace: ci
    tag: "4.18"
  tools:
    name: "4.15"
    namespace: ocp
    tag: tools
  upi-installer:
    name: "4.15"
    namespace: ocp
    tag: upi-installer
  verification-tests:
    name: verification-tests
    namespace: ci
    tag: latest
  vsphere-ci-python:
    name: vsphere-python
    namespace: ci
    tag: latest
releases:
  custom:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.18"
  intermediate1:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.16"
  intermediate2:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.17"
  intermediate3:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.18"
  latest:
    prerelease:
      architecture: amd64
      product: ocp
      version_bounds:
        lower: 4.15.0-0
        upper: 4.15.27-0
  target:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.19"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: baremetal-sno-agent-ipv4-static-connected-f28
  capabilities:
  - intranet
  cron: 7 15 13 * *
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      ADDITIONAL_WORKER_ARCHITECTURE: x86_64
      ADDITIONAL_WORKERS: "1"
      AGENT_PLATFORM_TYPE: none
      AUX_HOST: openshift-qe-metal-ci.arm.eng.rdu2.redhat.com
      RESERVE_BOOTSTRAP: "false"
      architecture: amd64
      ipv4_enabled: "true"
      ipv6_enabled: "false"
      masters: "1"
      workers: "0"
    test:
    - ref: cucushift-upgrade-setedge-4hops
    - chain: openshift-upgrade-qe-test-chainupgrade
    - ref: baremetal-lab-agent-day2
    workflow: baremetal-lab-agent-install-network-static
zz_generated_metadata:
  branch: release-4.19
  org: openshift
  repo: openshift-tests-private
  variant: amd64-nightly-4.19-upgrade-from-stable-4.15-OCPBUGS-43990
