base_images:
  ansible:
    name: "4.12"
    namespace: ocp
    tag: ansible
  aws-efs-csi-operator-create-efs:
    name: "4.12"
    namespace: ocp
    tag: aws-efs-csi-operator-create-efs
  cli:
    name: "4.12"
    namespace: ocp
    tag: cli
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  hypershift-operator:
    name: "4.12"
    namespace: ocp
    tag: hypershift-operator
  openstack-installer:
    name: "4.12"
    namespace: ocp
    tag: openstack-installer
  tests-private:
    name: tests-private
    namespace: ci
    tag: "4.12"
  tests-private-ui:
    name: tests-private-ui
    namespace: ci
    tag: "4.12"
  tools:
    name: "4.12"
    namespace: ocp
    tag: tools
  upi-installer:
    name: "4.12"
    namespace: ocp
    tag: upi-installer
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.18
releases:
  latest:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.12"
resources:
  '*':
    limits:
      memory: 8Gi
    requests:
      cpu: "1"
      memory: 4Gi
tests:
- as: baremetal-sno-ipv4-static-diskbyvendor-p1-f14
  cluster: build05
  cron: 30 17 7,21 * *
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      AUX_HOST: openshift-qe-bastion.arm.eng.rdu2.redhat.com
      DISCONNECTED: "false"
      DISK_BY_VENDOR: DELL
      INTERNAL_NET_CIDR: 192.168.90.0/24
      RESERVE_BOOTSTRAP: "false"
      architecture: amd64
      ipv4_enabled: "true"
      ipv6_enabled: "false"
      masters: "1"
      workers: "0"
    workflow: baremetal-lab-agent-install-network-static
zz_generated_metadata:
  branch: release-4.12
  org: openshift
  repo: openshift-tests-private
  variant: amd64-nightly-agent
