base_images:
  ansible:
    name: "4.15"
    namespace: ocp
    tag: ansible
  assisted-service-scripts:
    name: ocm-2.10
    namespace: edge-infrastructure
    tag: assisted-service-scripts
  aws-efs-csi-operator-create-efs:
    name: "4.15"
    namespace: ocp
    tag: aws-efs-csi-operator-create-efs
  cli:
    name: "4.15"
    namespace: ocp
    tag: cli
  cli-ocm:
    name: cli-ocm
    namespace: ci
    tag: latest
  cluster-api-actuator-pkg-test:
    name: cluster-api-actuator-pkg-test
    namespace: ci
    tag: "4.15"
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  hypershift-operator:
    name: hypershift-operator
    namespace: hypershift
    tag: latest
  hypershift-tests:
    name: hypershift-tests
    namespace: hypershift
    tag: latest
  openstack-installer:
    name: "4.15"
    namespace: ocp
    tag: openstack-installer
  rosa-aws-cli:
    name: rosa-aws-cli
    namespace: ci
    tag: release
  tests-private:
    name: tests-private
    namespace: ci
    tag: "4.15"
  tests-private-postupg:
    name: tests-private
    namespace: ci
    tag: "4.15"
  tests-private-preupg:
    name: tests-private
    namespace: ci
    tag: "4.15"
  tests-private-ui:
    name: tests-private-ui
    namespace: ci
    tag: "4.15"
  tools:
    name: "4.15"
    namespace: ocp
    tag: tools
  upi-installer:
    name: "4.15"
    namespace: ocp
    tag: upi-installer
  vsphere-ci-python:
    name: vsphere-python
    namespace: ci
    tag: latest
releases:
  custom:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.18"
  intermediate1:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.16"
  intermediate2:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.17"
  intermediate3:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.18"
  latest:
    prerelease:
      architecture: amd64
      product: ocp
      version_bounds:
        lower: 4.15.0-0
        upper: 4.15.26-0
  target:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.19"
resources:
  '*':
    limits:
      memory: 8Gi
    requests:
      cpu: "1"
      memory: 1Gi
tests:
- as: baremetal-sno-agent-ipv4-static-disc
  capabilities:
  - intranet
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      AGENT_PLATFORM_TYPE: none
      AUX_HOST: openshift-qe-metal-ci.arm.eng.rdu2.redhat.com
      FIPS_ENABLED: "false"
      RESERVE_BOOTSTRAP: "false"
      architecture: amd64
      ipv4_enabled: "true"
      ipv6_enabled: "false"
      masters: "1"
      workers: "0"
    workflow: baremetal-lab-agent-install-network-static-disconnected
zz_generated_metadata:
  branch: release-4.15
  org: openshift
  repo: openshift-tests-private
  variant: amd64-nightly-OCPBUGS-43990
