base_images:
  cli:
    name: "4.13"
    namespace: ocp
    tag: cli
  tests-private:
    name: tests-private
    namespace: ci
    tag: "4.13"
  tests-private-postupg:
    name: tests-private
    namespace: ci
    tag: "4.13"
  tests-private-preupg:
    name: tests-private
    namespace: ci
    tag: "4.13"
  tests-private-ui:
    name: tests-private-ui
    namespace: ci
    tag: "4.13"
  tools:
    name: "4.13"
    namespace: ocp
    tag: tools
  upi-installer:
    name: "4.13"
    namespace: ocp
    tag: upi-installer
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.18
releases:
  latest:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.13"
resources:
  '*':
    limits:
      memory: 8Gi
    requests:
      cpu: "1"
      memory: 4Gi
tests:
- as: baremetal-sno-dualstack-dynamic-disconnected
  cluster: build05
  cron: 30 17 7,21 * *
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      AUX_HOST: openshift-qe-bastion.arm.eng.rdu2.redhat.com
      DISCONNECTED: "true"
      INTERNAL_NET_CIDR: 192.168.90.0/24
      INTERNAL_NET_CIDR_V6: 2620:52:0:1eb::0/64
      RESERVE_BOOTSTRAP: "false"
      architecture: amd64
      ipv4_enabled: "true"
      ipv6_enabled: "true"
      masters: "1"
      workers: "0"
    workflow: baremetal-lab-agent-install-network-dynamic-disconnected
- as: baremetal-sno-dualstack-static-disconnected
  cluster: build05
  cron: 30 17 7,21 * *
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      AUX_HOST: openshift-qe-bastion.arm.eng.rdu2.redhat.com
      DISCONNECTED: "true"
      INTERNAL_NET_CIDR: 192.168.90.0/24
      INTERNAL_NET_CIDR_V6: 2620:52:0:1eb::0/64
      RESERVE_BOOTSTRAP: "false"
      architecture: amd64
      ipv4_enabled: "true"
      ipv6_enabled: "true"
      masters: "1"
      workers: "0"
    workflow: baremetal-lab-agent-install-network-static-disconnected
- as: baremetal-sno-dualstack-static-connected
  cluster: build05
  cron: 30 17 7,21 * *
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      AUX_HOST: openshift-qe-bastion.arm.eng.rdu2.redhat.com
      DISCONNECTED: "false"
      INTERNAL_NET_CIDR: 192.168.90.0/24
      INTERNAL_NET_CIDR_V6: 2620:52:0:1eb::0/64
      RESERVE_BOOTSTRAP: "false"
      architecture: amd64
      ipv4_enabled: "true"
      ipv6_enabled: "true"
      masters: "1"
      workers: "0"
    workflow: baremetal-lab-agent-install-network-static
- as: baremetal-sno-dualstack-dynamic-connected
  cluster: build05
  cron: 30 17 7,21 * *
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      AUX_HOST: openshift-qe-bastion.arm.eng.rdu2.redhat.com
      DISCONNECTED: "false"
      INTERNAL_NET_CIDR: 192.168.90.0/24
      INTERNAL_NET_CIDR_V6: 2620:52:0:1eb::0/64
      RESERVE_BOOTSTRAP: "false"
      architecture: amd64
      ipv4_enabled: "true"
      ipv6_enabled: "true"
      masters: "1"
      workers: "0"
    workflow: baremetal-lab-agent-install-network-dynamic
zz_generated_metadata:
  branch: release-4.13
  org: openshift
  repo: openshift-tests-private
  variant: amd64-nightly-agent
