base_images:
  ansible:
    name: "4.16"
    namespace: ocp
    tag: ansible
  aws-efs-csi-operator-create-efs:
    name: "4.16"
    namespace: ocp
    tag: aws-efs-csi-operator-create-efs
  cli:
    name: "4.16"
    namespace: ocp
    tag: cli
  cli-ocm:
    name: cli-ocm
    namespace: ci
    tag: latest
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  hypershift-operator:
    name: "4.16"
    namespace: ocp
    tag: hypershift-operator
  openstack-installer:
    name: "4.16"
    namespace: ocp
    tag: openstack-installer
  rosa-aws-cli:
    name: rosa-aws-cli
    namespace: ci
    tag: latest
  tests-private:
    name: tests-private
    namespace: ci
    tag: "4.16"
  tests-private-postupg:
    name: tests-private
    namespace: ci
    tag: "4.16"
  tests-private-preupg:
    name: tests-private
    namespace: ci
    tag: "4.16"
  tests-private-ui:
    name: tests-private-ui
    namespace: ci
    tag: "4.16"
  tools:
    name: "4.16"
    namespace: ocp
    tag: tools
  upi-installer:
    name: "4.16"
    namespace: ocp
    tag: upi-installer
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.18
releases:
  latest:
    candidate:
      architecture: amd64
      product: ocp
      stream: ci
      version: "4.16"
  multi-latest:
    candidate:
      architecture: multi
      product: ocp
      stream: ci
      version: "4.16"
  target:
    candidate:
      architecture: multi
      product: ocp
      stream: ci
      version: "4.16"
resources:
  '*':
    limits:
      memory: 8Gi
    requests:
      cpu: "1"
      memory: 1Gi
tests:
- as: baremetal-compact-agent-platform-none-ipv4-static-f14
  cluster: build05
  cron: 53 15 11,25 * *
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      AGENT_PLATFORM_TYPE: none
      AUX_HOST: openshift-qe-metal-ci.arm.eng.rdu2.redhat.com
      DISCONNECTED: "false"
      EXTRA_MANIFEST_PATH: releases/23.1/ocp
      EXTRA_MANIFEST_URL: https://github.com/Juniper/contrail-networking.git
      RESERVE_BOOTSTRAP: "false"
      architecture: amd64
      ipv4_enabled: "true"
      ipv6_enabled: "false"
      masters: "3"
      workers: "0"
    workflow: baremetal-lab-agent-install-network-static
zz_generated_metadata:
  branch: release-4.16
  org: openshift
  repo: openshift-tests-private
  variant: amd64-ci
