base_images:
  cli:
    name: "4.14"
    namespace: ocp
    tag: cli
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.18
releases:
  latest:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.14"
resources:
  '*':
    limits:
      memory: 8Gi
    requests:
      cpu: "1"
      memory: 4Gi
tests:
- as: baremetal-agent-ipv4-connected-sno-static
  cluster: build05
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      AUX_HOST: openshift-qe-bastion.arm.eng.rdu2.redhat.com
      INTERNAL_NET_CIDR: 192.168.90.0/24
      RESERVE_BOOTSTRAP: "false"
      architecture: amd64
      ipv4_enabled: "true"
      ipv6_enabled: "false"
      masters: "1"
      workers: "0"
    observers:
      enable:
      - observers-ocp-baremetal-qe-oink-vnc
      - observers-ocp-baremetal-qe-oink-systemd-journalctl
    workflow: baremetal-lab-agent-install-network-static
- as: baremetal-agent-ipv4-disconnected-sno-static-fips
  cluster: build05
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      AUX_HOST: openshift-qe-bastion.arm.eng.rdu2.redhat.com
      FIPS_ENABLED: "true"
      INTERNAL_NET_CIDR: 192.168.90.0/24
      RESERVE_BOOTSTRAP: "false"
      architecture: amd64
      ipv4_enabled: "true"
      ipv6_enabled: "false"
      masters: "1"
      workers: "0"
    observers:
      enable:
      - observers-ocp-baremetal-qe-oink-vnc
      - observers-ocp-baremetal-qe-oink-systemd-journalctl
    workflow: baremetal-lab-agent-install-network-static-disconnected
- as: baremetal-agent-ipv4-disconnected-sno-static-proxy
  cluster: build05
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      AUX_HOST: openshift-qe-bastion.arm.eng.rdu2.redhat.com
      INTERNAL_NET_CIDR: 192.168.90.0/24
      RESERVE_BOOTSTRAP: "false"
      architecture: amd64
      ipv4_enabled: "true"
      ipv6_enabled: "false"
      masters: "1"
      workers: "0"
    observers:
      enable:
      - observers-ocp-baremetal-qe-oink-vnc
      - observers-ocp-baremetal-qe-oink-systemd-journalctl
    workflow: baremetal-lab-agent-install-network-static-disconnected-proxy
- as: baremetal-agent-ipv6-disconnected-sno-static
  cluster: build05
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      ARCHITECTURE: amd64
      AUX_HOST: openshift-qe-055.arm.eng.rdu2.redhat.com
      BASE_DOMAIN: agentinstaller.com
      CLUSTER_NAME: 414-sno-v6-dis-st
      DEPLOYMENT_TYPE: sno
      DISCONNECTED: "true"
      FIPS: "false"
      IP_STACK: v6
      PROXY: "false"
    observers:
      enable:
      - observers-ocp-baremetal-qe-oink-vnc
      - observers-ocp-baremetal-qe-oink-systemd-journalctl
    workflow: baremetal-lab-agent-ansible
- as: baremetal-agent-ipv6-disconnected-compact-static
  cluster: build05
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      ARCHITECTURE: amd64
      AUX_HOST: openshift-qe-055.arm.eng.rdu2.redhat.com
      BASE_DOMAIN: agentinstaller.com
      CLUSTER_NAME: 414-cmp-v6-dis-st
      DEPLOYMENT_TYPE: compact
      DISCONNECTED: "true"
      FIPS: "false"
      IP_STACK: v6
      PROXY: "false"
    observers:
      enable:
      - observers-ocp-baremetal-qe-oink-vnc
      - observers-ocp-baremetal-qe-oink-systemd-journalctl
    workflow: baremetal-lab-agent-ansible
- as: baremetal-agent-dualstack-disconnected-sno-static
  cluster: build05
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      ARCHITECTURE: amd64
      AUX_HOST: openshift-qe-055.arm.eng.rdu2.redhat.com
      BASE_DOMAIN: agentinstaller.com
      CLUSTER_NAME: 414-sno-v4v6-dis-st
      DEPLOYMENT_TYPE: sno
      DISCONNECTED: "true"
      FIPS: "false"
      IP_STACK: v4v6
      PROXY: "false"
    observers:
      enable:
      - observers-ocp-baremetal-qe-oink-vnc
      - observers-ocp-baremetal-qe-oink-systemd-journalctl
    workflow: baremetal-lab-agent-ansible
- as: baremetal-agent-dualstack-connected-sno-static
  cluster: build05
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      ARCHITECTURE: amd64
      AUX_HOST: openshift-qe-055.arm.eng.rdu2.redhat.com
      BASE_DOMAIN: agentinstaller.com
      CLUSTER_NAME: 414-sno-v4v6-st
      DEPLOYMENT_TYPE: sno
      DISCONNECTED: "false"
      FIPS: "false"
      IP_STACK: v4v6
      PROXY: "false"
    observers:
      enable:
      - observers-ocp-baremetal-qe-oink-vnc
      - observers-ocp-baremetal-qe-oink-systemd-journalctl
    workflow: baremetal-lab-agent-ansible
- as: baremetal-agent-dualstack-disconnected-compact-static
  cluster: build05
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      ARCHITECTURE: amd64
      AUX_HOST: openshift-qe-055.arm.eng.rdu2.redhat.com
      BASE_DOMAIN: agentinstaller.com
      CLUSTER_NAME: 414-cmp-v4v6-dis-st
      DEPLOYMENT_TYPE: compact
      DISCONNECTED: "true"
      FIPS: "false"
      IP_STACK: v4v6
      PROXY: "false"
    observers:
      enable:
      - observers-ocp-baremetal-qe-oink-vnc
      - observers-ocp-baremetal-qe-oink-systemd-journalctl
    workflow: baremetal-lab-agent-ansible
- as: baremetal-agent-dualstack-connected-compact-static
  cluster: build05
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      ARCHITECTURE: amd64
      AUX_HOST: openshift-qe-055.arm.eng.rdu2.redhat.com
      BASE_DOMAIN: agentinstaller.com
      CLUSTER_NAME: 414-cmp-v4v6-st
      DEPLOYMENT_TYPE: compact
      DISCONNECTED: "false"
      FIPS: "false"
      IP_STACK: v4v6
      PROXY: "false"
    observers:
      enable:
      - observers-ocp-baremetal-qe-oink-vnc
      - observers-ocp-baremetal-qe-oink-systemd-journalctl
    workflow: baremetal-lab-agent-ansible
zz_generated_metadata:
  branch: release-4.14
  org: openshift
  repo: openshift-tests-private
  variant: amd64-nightly-agent-qe
