base_images:
  cli:
    name: "4.17"
    namespace: ocp
    tag: cli
  cli-ocm:
    name: cli-ocm
    namespace: ci
    tag: latest
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  tests-private:
    name: tests-private
    namespace: ci
    tag: "4.17"
  tests-private-postupg:
    name: tests-private
    namespace: ci
    tag: "4.17"
  tests-private-preupg:
    name: tests-private
    namespace: ci
    tag: "4.17"
  tests-private-ui:
    name: tests-private-ui
    namespace: ci
    tag: "4.17"
  tools:
    name: "4.17"
    namespace: ocp
    tag: tools
  upi-installer:
    name: "4.17"
    namespace: ocp
    tag: upi-installer
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.18
releases:
  latest:
    candidate:
      architecture: amd64
      product: ocp
      stream: ci
      version: "4.17"
resources:
  '*':
    limits:
      memory: 8Gi
    requests:
      cpu: "1"
      memory: 1Gi
tests:
- as: baremetal-sno-abi-ipv4-static-day2-f7
  cluster: build05
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      ADDITIONAL_WORKER_ARCHITECTURE: x86_64
      ADDITIONAL_WORKERS: "3"
      AGENT_PLATFORM_TYPE: none
      AUX_HOST: openshift-qe-metal-ci.arm.eng.rdu2.redhat.com
      CLUSTER_DURATION: "72000"
      FIPS_ENABLED: "false"
      RESERVE_BOOTSTRAP: "false"
      architecture: amd64
      ipv4_enabled: "true"
      ipv6_enabled: "false"
      masters: "1"
      workers: "0"
    workflow: baremetal-lab-agent-install-network-static-day2-abi
- as: baremetal-sno-abi-ipv4-static-disc-day2-f7
  cluster: build05
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      ADDITIONAL_WORKER_ARCHITECTURE: x86_64
      ADDITIONAL_WORKERS: "3"
      AGENT_PLATFORM_TYPE: none
      AUX_HOST: openshift-qe-metal-ci.arm.eng.rdu2.redhat.com
      FIPS_ENABLED: "false"
      RESERVE_BOOTSTRAP: "false"
      architecture: amd64
      ipv4_enabled: "true"
      ipv6_enabled: "false"
      masters: "1"
      workers: "0"
    workflow: baremetal-lab-agent-install-network-static-disconnected-day2-abi
- as: baremetal-sno-abi-ipv4-static-disc-proxy-day2-f7
  cluster: build05
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      ADDITIONAL_WORKER_ARCHITECTURE: x86_64
      ADDITIONAL_WORKERS: "1"
      AGENT_PLATFORM_TYPE: none
      AUX_HOST: openshift-qe-metal-ci.arm.eng.rdu2.redhat.com
      FIPS_ENABLED: "false"
      RESERVE_BOOTSTRAP: "false"
      architecture: amd64
      ipv4_enabled: "true"
      ipv6_enabled: "false"
      masters: "1"
      workers: "0"
    workflow: baremetal-lab-agent-install-network-static-disconnected-day2-abi-proxy
zz_generated_metadata:
  branch: release-4.17
  org: openshift
  repo: openshift-tests-private
  variant: amd64-ci
