base_images:
  cli:
    name: "4.17"
    namespace: ocp
    tag: cli
  tools:
    name: "4.17"
    namespace: ocp
    tag: tools
  upi-installer:
    name: "4.17"
    namespace: ocp
    tag: upi-installer
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.18
releases:
  latest:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.17"
  multi-latest:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: "4.17"
  target:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: "4.17"
resources:
  '*':
    limits:
      memory: 8Gi
    requests:
      cpu: "1"
      memory: 1Gi
tests:
- as: baremetal-compact-agent-ipv4-static-connected-f14
  cluster: build05
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      AUX_HOST: openshift-qe-metal-ci.arm.eng.rdu2.redhat.com
      RESERVE_BOOTSTRAP: "false"
      architecture: amd64
      ipv4_enabled: "true"
      ipv6_enabled: "false"
      masters: "3"
      workers: "0"
    workflow: baremetal-lab-agent-install-network-static
zz_generated_metadata:
  branch: release-4.17
  org: openshift
  repo: openshift-tests-private
  variant: amd64-test
