base_images:
  cli:
    name: "4.18"
    namespace: ocp
    tag: cli
  tools:
    name: "4.18"
    namespace: ocp
    tag: tools
  upi-installer:
    name: "4.18"
    namespace: ocp
    tag: upi-installer
releases:
  latest:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.18"
  multi-latest:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: "4.18"
  target:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: "4.18"
resources:
  '*':
    limits:
      memory: 8Gi
    requests:
      cpu: "1"
      memory: 1Gi
tests:
- as: baremetal-sno-agent-ipv4-static-connected-fips-f7
  cluster: build05
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      AGENT_PLATFORM_TYPE: none
      AUX_HOST: openshift-qe-metal-ci.arm.eng.rdu2.redhat.com
      FIPS_ENABLED: "true"
      RESERVE_BOOTSTRAP: "false"
      architecture: amd64
      ipv4_enabled: "true"
      ipv6_enabled: "false"
      masters: "1"
      workers: "0"
    workflow: baremetal-lab-agent-install-network-static
zz_generated_metadata:
  branch: release-4.18
  org: openshift
  repo: openshift-tests-private
  variant: amd64-test
