base_images:
  cli:
    name: "4.14"
    namespace: ocp
    tag: cli
  tests-private:
    name: tests-private
    namespace: ci
    tag: "4.14"
  tools:
    name: "4.14"
    namespace: ocp
    tag: tools
  upi-installer:
    name: "4.14"
    namespace: ocp
    tag: upi-installer
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.18
releases:
  latest:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.14"
  multi-latest:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: "4.14"
  target:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: "4.14"
resources:
  '*':
    limits:
      memory: 8Gi
    requests:
      cpu: "1"
      memory: 4Gi
tests:
- as: baremetal-sno-ipv4-static-p1-f14
  cluster: build05
  cron: 30 17 7,21 * *
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      AUX_HOST: openshift-qe-bastion.arm.eng.rdu2.redhat.com
      DISCONNECTED: "false"
      INTERNAL_NET_CIDR: 192.168.90.0/24
      RESERVE_BOOTSTRAP: "false"
      architecture: amd64
      ipv4_enabled: "true"
      ipv6_enabled: "false"
      masters: "1"
      workers: "0"
    workflow: baremetal-lab-agent-install-network-static
zz_generated_metadata:
  branch: release-4.14
  org: openshift
  repo: openshift-tests-private
  variant: amd64-nightly-agent
