workflow:
  as: baremetal-lab-agent-ansible
  steps:
    pre:
      - chain: baremetal-lab-agent-ansible-conf
      - ref: baremetal-lab-agent-ansible-install
      - ref: baremetal-lab-agent-ansible-install-wait-for-bootstrap-complete
      - ref: baremetal-lab-agent-ansible-install-wait-for-install-complete
      - ref: baremetal-lab-agent-ansible-install-get-nodes
      - ref: baremetal-lab-agent-ansible-install-describe-network
    post:
      - ref: baremetal-lab-agent-ansible-post-release-nodes
      #- chain: baremetal-lab-agent-post
  documentation: |-
    The baremetal-lab-agent-ansible workflow provides pre- and post- steps that provision and
    deprovision an agent based OpenShift cluster with a default configuration on a Baremetal lab,
    allowing job authors to inject their own end-to-end test logic.
